# Generated by Django 5.0.6 on 2024-07-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_dailybalance_uid_alter_dailybalance_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailybalance',
            name='uid',
        ),
        migrations.AlterField(
            model_name='dailybalance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
